//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5GJN22E\\SQLEXPRESS;Initial Catalog=testluong;Persist Security" +
            " Info=False;User ID=sa;Password=123;Encrypt=True;TrustServerCertificate=True")]
        public string testluongConnectionString {
            get {
                return ((string)(this["testluongConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5GJN22E\\SQLEXPRESS;Initial Catalog=SieuThi7;User ID=sa;Passwo" +
            "rd=123;Persist Security Info=False;Encrypt=True;TrustServerCertificate=True")]
        public string SieuThi7ConnectionString {
            get {
                return ((string)(this["SieuThi7ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5GJN22E\\SQLEXPRESS;Initial Catalog=SieuThi8;Persist Security " +
            "Info=True;User ID=sa;Password=123;TrustServerCertificate=True")]
        public string SieuThi8ConnectionString {
            get {
                return ((string)(this["SieuThi8ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5GJN22E\\SQLEXPRESS;Initial Catalog=SieuThi;Persist Security I" +
            "nfo=True;User ID=sa;Password=123;TrustServerCertificate=True")]
        public string SieuThiConnectionString {
            get {
                return ((string)(this["SieuThiConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5GJN22E\\SQLEXPRESS;Initial Catalog=SieuThi9;Persist Security " +
            "Info=True;User ID=sa;Password=123;TrustServerCertificate=True")]
        public string SieuThi9ConnectionString {
            get {
                return ((string)(this["SieuThi9ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Dainn;Initial Catalog=SieuThi;Integrated Security=True;Encrypt=True;T" +
            "rustServerCertificate=True")]
        public string SieuThiConnectionString1 {
            get {
                return ((string)(this["SieuThiConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=26.129.163.219;Initial Catalog=SieuThi;Persist Security Info=True;Use" +
            "r ID=serverQLST;Password=21062024;TrustServerCertificate=True")]
        public string SieuThiConnectionString2 {
            get {
                return ((string)(this["SieuThiConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.203.36,1433;Initial Catalog=SieuThi;Persist Security Info=Tru" +
            "e;User ID=serverQLST;Password=21062024;TrustServerCertificate=True")]
        public string SieuThiConnectionString3 {
            get {
                return ((string)(this["SieuThiConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.85.36,1433;Initial Catalog=SieuThi;Persist Security Info=True" +
            ";User ID=serverQLST;Password=21062024;TrustServerCertificate=True")]
        public string SieuThiConnectionString4 {
            get {
                return ((string)(this["SieuThiConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Dainn;Initial Catalog=SieuThi;Integrated Security=True;TrustServerCer" +
            "tificate=True")]
        public string SieuThiConnectionString5 {
            get {
                return ((string)(this["SieuThiConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VANHAU\\HAUDEPTRAI;Initial Catalog=SieuThi;Persist Security Info=True;" +
            "User ID=sa;Password=123;TrustServerCertificate=True")]
        public string SieuThiConnectionString6 {
            get {
                return ((string)(this["SieuThiConnectionString6"]));
            }
        }
    }
}
